### ISSUE TITLE
Executed markdown: fenced output block no new line before it

### ISSUE THREAD

**Issue by liuyxpp** [fredrikekre/Literate.jl#101]
I believe there should be one new line between the code block and the output block according to Markdown rules.
Current workaround: configure the `codefence` to <code>"\`\`\`julia" => "\`\`\`\\n"</code>. But it will add an extra new line (two new lines) after the output block.

**Comment by fredrikekre** [comment]
>Markdown rules

Which rules are you refering to?

**Comment by liuyxpp** [comment]
See https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md - MD031

> Rationale: Aside from aesthetic reasons, some parsers, including kramdown, will not parse fenced code blocks that don't have blank lines before and after them.

Although it may not violate the official markdown rules, it is still a good practice to leave a blank line between two code blocks.
