### ISSUE TITLE
Nbviewer/Binder links should work in /previews/PRXX/?

### ISSUE THREAD

**Issue by navidcy** [fredrikekre/Literate.jl#104]
I'm wondering if the nbviewer/binder badge links should work in previews or whether I'm doing something wrong. See, e.g., here:
https://fourierflows.github.io/GeophysicalFlows.jl/previews/PR70/generated/twodnavierstokes_decaying/

**Comment by fredrikekre** [comment]
Yea, it should work. The notebook link is correct if you change `example` to `generated` (https://nbviewer.jupyter.org/github/FourierFlows/GeophysicalFlows.jl/blob/gh-pages/previews/PR70/generated/twodnavierstokes_decaying.ipynb) but not sure why it put `examples` there in the first place.

**Comment by navidcy** [comment]
oops.. my bad; a left over from a previous commit in which output files were put in a directory called `/examples/`. thanks!

but the `binder` badge still doesn't work:
> Could not find a kernel matching Julia 1.4.1.
I presume because there are no `.toml` files in the `/generated/`. Shall I just add a command to copy them from `repo/examples/` dir to `OUTPUT_DIR` after `Literate.notebook()`?

**Comment by fredrikekre** [comment]
> Could not find a kernel matching Julia 1.4.1.

Maybe binder does not have 1.4.1 yet?

> I presume because there are no .toml files in the /generated/. Shall I just add a command to copy them from repo/examples/ dir to OUTPUT_DIR after Literate.notebook()?

I believe that for binder to work correctly you need the toml files in the root of the branch, see e.g. https://github.com/fredrikekre/Literate.jl/tree/gh-pages

**Comment by fredrikekre** [comment]
> > Could not find a kernel matching Julia 1.4.1.
> 
> Maybe binder does not have 1.4.1 yet?

It works for the example in Literate docs, so maybe you just need to add the toml files to tell binder that it is a julia notebook.
