### ISSUE TITLE
Suggestion: being able to turn a notebook into a script

### ISSUE THREAD

**Issue by sgaseretto** [fredrikekre/Literate.jl#107]
I've been doing Literate Programming in Python and the experience so far is amazing. In order to have code that explains itself and also that could be bundled into a package, I'm using this awesome library called [nbdev](https://nbdev.fast.ai/) that allows you to write your code in Jupyter Notebooks and then you can export the cells from the functions and code you want to reuse in new notebooks or scripts. This week I started learning Julia and immediately started missing this feature, so googling a little bit I found this awesome package, it allows you to return a Notebook from a commented Julia script. Are any plans on adding a feature that allows you to do the inverse thing? It would be an awesome feature for the ones that mainly use Jupyter as their development tool.

**Comment by KristofferC** [comment]
I think this is the same as https://github.com/fredrikekre/Literate.jl/issues/106
