### ISSUE TITLE
PyPlot plots do not render

### ISSUE THREAD

**Issue by moustachio-belvedere** [fredrikekre/Literate.jl#111]
This package is great, thanks very much for developing it. I noticed something that may be a bug, apologies if it is expected behaviour, or perhaps caused by Documenter.jl or jupyter notebooks.

My go-to plotting package is PyPlot as I'm very comfortable with the API. However, when locally generating some documentation (with Documenter.jl) from a .jl source file, converted into markdown with Literate.jl (https://github.com/moustachio-belvedere/JuliaPackageDemo.jl/blob/master/docs/src/simpleexamples.jl), the `plot` command just returns the literal plot object:

```
1-element Array{PyCall.PyObject,1}:
 PyObject <matplotlib.lines.Line2D object at 0x0000000045B6FE48>
```

Using Plots.jl instead of PyPlot.jl immediately resolves the issue and a plot renders correctly. Is there a way to get PyPlot to properly render plots? I tried adding the `show()` command without success.

**Comment by Paveloom** [comment]
Hi, @moustachio-belvedere. I literally just ran into this same problem and found a solution in the already existing issue #36, that is, to add `gcf()` at the end.

**Comment by fredrikekre** [comment]
Sorry, must have missed this issue. But as @Paveloom says, it is about what is returned from PyPlot. I don't know why they don't just return the figure handle, but you need `gcf()` to obtain it.
