### ISSUE TITLE
A compound example for admonitions

### ISSUE THREAD

**Issue by moustachio-belvedere** [fredrikekre/Literate.jl#112]
Might be nice to add a compound example of line filtering in the docs for admonitions. I'm happy to add in a PR if you like. For example, earlier today I was confused why an admonition was being parsed into an example block in line below it, i.e.

```
#md  !!! note "Beware!"
#md      Admonitions are a useful feature of Documenter.jl which would be tricky to use directly from Notebook-derived markdown.

## get time vector
timevec = collect(0:0.1:10)
```
I didn't want the admonition code to show if I converted to a notebook. It took me a while to realise that to stop it being parsed as part of the code block I needed to add another `#` to signify beginning of a markdown line as well:
```
#md # !!! note "Beware!"
#md #     Admonitions are a useful feature of Documenter.jl which would be tricky to use directly from Notebooks.
```

edit: Just found one in your docs source at https://github.com/fredrikekre/Literate.jl/blob/master/examples/example.jl#L75 -- maybe that would be a reasonable place in the docs to explain how the admonition was generated.

**Comment by fredrikekre** [comment]
Could add it to the new tips and tricks section. Do you want to make a PR? Could also include https://github.com/fredrikekre/Literate.jl/issues/64#issuecomment-512250927 in that section.

**Comment by moustachio-belvedere** [comment]
Sounds good, I'll try send a PR tonight or over the weekend.

**Comment by moustachio-belvedere** [comment]
PR made in https://github.com/fredrikekre/Literate.jl/pull/115
