### ISSUE TITLE
Replace inline backtick math in notebooks

### ISSUE THREAD

**Issue by mortenpi** [fredrikekre/Literate.jl#116]
Literate replaces the ` ```math` blocks with `$$`s when run outputting notebooks:

https://github.com/fredrikekre/Literate.jl/blob/c1dce7ff56c53f813956ff5b00cfcbab9328800b/src/Literate.jl#L163

But not the inline elements (`foo ``x^2`` bar`), which then don't render properly (would need `$`s). Should we also add e.g. this:

```julia
push!(repls, r"``(.+)``" => s"$\1$")
```

to the default replacements?

**Comment by mortenpi** [comment]
I noticed that the original regex was overly greedy. This one seems to work better (matches everything between 2 backticks, except for newlines and backticks):

```julia
r"``([^`\n]+)``" => s"$\1$"
```

**Comment by moustachio-belvedere** [comment]
This would be very nice to have for documentation I'm working on. I'm not knowledgeable enough to create a PR, but I was wondering if there is a temporary work-around that can be used?
