### ISSUE TITLE
Limit the number of rows when printing out DataFrame

### ISSUE THREAD

**Issue by FuZhiyu** [fredrikekre/Literate.jl#127]
This is related to another issue #125. 

When mixing code and texts it's very common to forget to end the last code cell with a ';'. It would be very problematic if the last cell returns a huge `DataFrame` with millions of rows (as is often the case for data work). By default all rows will be printed out into the markdown file, paralyzing the whole Julia session. 

It seems the issue is caused by that [the method `show defined for DataFrame`](https://dataframes.juliadata.org/stable/lib/functions/#Base.show) specifies that when `io` is provided, the default is showing all rows, unless `io` does not have the `IOContext` property `limit` set. i.e.
```
allrows::Bool = !get(io, :limit, false)
```

For my own usage, I can temporarily override the show function by

```
Base.show(io::IO, ::MIME"text/plain", dt::AbstractDataFrame) = show(io, dt; allrows = false)
```
but I think it may be an issue worth discussion. Do you think it's reasonable to set the property `limit` for the IOstream to be `true`?  It seems reasonable to me, but I don't know how other people are using this package. At any rate it could be an option for users to decide.  Or can we add another `if` branch specialized to deal with `DataFrame`?

**Comment by fredrikekre** [comment]
> Do you think it's reasonable to set the property limit for the IOstream to be true?

Do you know if Documenter does this? I think some way of configuring the IO context would be good. Perhaps using some similar things as `Unlimited` from https://github.com/tkf/DisplayAs.jl

**Comment by fredrikekre** [comment]
https://github.com/tkf/DisplayAs.jl/pull/14

**Comment by fredrikekre** [comment]
https://github.com/tkf/DisplayAs.jl/pull/14 is merged now so I suggest people use that.
