### ISSUE TITLE
Fetching output of display

### ISSUE THREAD

**Issue by bkamins** [fredrikekre/Literate.jl#128]
I have the following question. I have a file:
```
function f()
    display([1 2; 3 4])
end

f()
```
called `test.jl`.

Now I run:
```
julia> Literate.markdown("test.jl", execute=true)
[ Info: generating markdown page from `D:\test.jl`
2×2 Array{Int64,2}:
 1  2
 3  4
[ Info: writing result to `D:\test.md`
"D:\\test.md"

julia> Literate.notebook("test.jl", execute=true)
[ Info: generating notebook from `D:\test.jl`
[ Info: executing notebook `test.ipynb`
2×2 Array{Int64,2}:
 1  2
 3  4
[ Info: writing result to `D:\test.ipynb`
"D:\\test.ipynb"
```
and `display` result is produced in the Julia session not in the markdown neither notebook. Is there a way to work around this? Thank you!

**Comment by fredrikekre** [comment]
Sorry, didn't see this issue until now.

I am not sure how to catch `display`. I guess Literate would have to define a `display` and push that to the display stack: https://github.com/JuliaLang/julia/blob/c1c52930bb58605b60ae723c28f63e43b73944f6/base/multimedia.jl#L260

Why do you want to use `display` and not `show` though? I don't think I have ever called `display` myself, that is usually called by the REPL/IJulia backend.

**Comment by bkamins** [comment]
In Jupyter Notebook you have to call `display` if you want HTML-formatted output produced in the middle of your computation, e.g. run the following code:
```
using DataFrames
foreach(display, [DataFrame(a=1), DataFrame(b=2)])
```
vs
```
using DataFrames
foreach(show, [DataFrame(a=1), DataFrame(b=2)])
```

**Comment by fredrikekre** [comment]
Thanks. I thought it would be as simple as this:
```
show(stdout, MIME"text/html"(), df)
```
but apparently not.

**Comment by bkamins** [comment]
This is the point `stdout` does not work in Jupyter Notebook AFAICT

**Comment by fredrikekre** [comment]
Works in 2.8.0 (https://github.com/JuliaRegistries/General/pull/28270).

**Comment by bkamins** [comment]
Thank you for looking into it. I have left a comment about how IJulia.jl works in your commit
