### ISSUE TITLE
Images created with GMT are not displayed in Documenter

### ISSUE THREAD

**Issue by joa-quim** [fredrikekre/Literate.jl#134]
When I try to generate a markdown to include in Documenter all is fine except that the images are not included. When compiling the Documenter files I see that those figures get correctly generated and displayed in popuped windows (PNGs or PostScript) but not included. Note that the same commands work fine in Pluto and Jupyter notebooks.

Not sure what else can I add to help further.

**Comment by fredrikekre** [comment]
> Not sure what else can I add to help further.

A code example would be nice

**Comment by joa-quim** [comment]
Hmm, yes it would. This
[test_literate.md.zip](https://github.com/fredrikekre/Literate.jl/files/5951512/test_literate.md.zip)
should produce the same as in this [discourse thread](https://discourse.julialang.org/t/draw-surface-with-contours-plot-underneath/54813/3?u=joa-quim) and in fact it does generate the PNG file but it's not included in the html.

But note that GMT.jl does not install GMT.
Instructions for installing in linux are [here](https://github.com/GenericMappingTools/gmt/blob/master/INSTALL.md#linux)

**Comment by fredrikekre** [comment]
Is this still an issue? Sorry for the late response.
