### ISSUE TITLE
Feature request: filters for documenter vs vanilla markdown

### ISSUE THREAD

**Issue by guyvdbroeck** [fredrikekre/Literate.jl#139]
I would like to include the same code examples in my auto-generated README.md and in my Documenter,jl documentation. Unfortunately the former doesn't seem to support images, while the latter does. It would be great if I could make those image examples conditional on `documenter==true`

**Comment by fredrikekre** [comment]
> Unfortunately the former doesn't seem to support images

Why not?

**Comment by fredrikekre** [comment]
Closing as stale, please comment if this is still an issue.
