### ISSUE TITLE
Building docs is freezing

### ISSUE THREAD

**Issue by francispoulin** [fredrikekre/Literate.jl#140]
I am trying to build docs for Oceananigans on my local computer and it seems to build the markdown very quickly.  Then, when it's time to do other things, it seems to get stuck at this line:

[ Info: ExpandTemplates: expanding markdown templates.

When I look at `top` it doesn't seem to be doing anything.  Any advice on how I might monitor the progress to see what it's doing if anything?

**Comment by KristofferC** [comment]
Probably https://github.com/fredrikekre/Literate.jl/issues/138, could try with the patch I posted in https://github.com/fredrikekre/Literate.jl/issues/138#issuecomment-796525480.

**Comment by francispoulin** [comment]
Thanks @KristofferC .  I will look at the example and see if I can figure out how I might apply this patch to my problem.
