### ISSUE TITLE
How to skip code parsing/evalaution/testing for quick preview of the documentation ?

### ISSUE THREAD

**Issue by sylvaticus** [fredrikekre/Literate.jl#142]
As my doc includes some tutorials it takes ages to build.
Is there a way, similar to Documenter's `doctest=false` in `makedocs that I can use to skip parsing/evaluaiton and testing of the code blocks and just see how the documentation is rendered ? Ideally then I could just add a parameter to make.jl as "preview" or "quick" when I want skip the code evaluation.

**Comment by fredrikekre** [comment]
Answered on Discourse: https://discourse.julialang.org/t/literate-jl-how-to-skip-code-parsing-testing-for-quick-generation-and-preview-of-the-documentation/58603
