### ISSUE TITLE
Build loop on Literate to Documenter build

### ISSUE THREAD

**Issue by cadojo** [fredrikekre/Literate.jl#148]
I _wanna_ say this could be a bug, but it's probably a user error. Still, I haven't been able to figure it out. This issue is identical to a previously posted [Discourse](https://discourse.julialang.org/t/literate-scripts-within-documenter-cause-liveserver-loop/63319) post. 

I'm trying to use `Literate` to autogenerate pages for my `Documenter` site. The repo is [here](https://github.com/cadojo/ControlTheoryNotes.jl). If I...

```
git clone https://github.com/cadojo/ControlTheoryNotes.jl
cd ControlTheoryNotes.jl
julia --project=docs
julia> import Pkg; Pkg.instantiate()
julia> cd("docs")
julia> using LiveServer; LiveServer.servedocs(; literate = joinpath(@__DIR__, "docs", "src", "generated"))
```

I get a build loop where it just continues building the entire site forever. Is there anything glaring about what I'm doing here?

In the process, I get the following warning.

```julia
┌ Warning: couldn't find file "/private/tmp/ControlTheoryNotes.jl/docs/src/generated/<unknown>/src/Chapter 1: Dynamics.jl" when generating URL
```

**Comment by fredrikekre** [comment]
I don't quite know how that works, maybe @tlienart can give some more input.

**Comment by tlienart** [comment]
sorry for the delay; maybe this issue could be transferred over to LiveServer

@cadojo I just cloned your repo and was not able to find the `generated` dir. Could you maybe prepare a branch for me to reproduce your case? Ideally drop the `--project` stuff, and can I just check that you followed https://tlienart.github.io/LiveServer.jl/dev/man/ls+lit/#LiveServer-Literate ?

**Comment by fredrikekre** [comment]
I think this has been improved in LiveServer.jl
