### ISSUE TITLE
support markdown strings as comment blocks

### ISSUE THREAD

**Issue by CarloLucibello** [fredrikekre/Literate.jl#149]
As an alternative to (or in addition to) current comment blocks identified by `#`, Literate could support multi-line markdown strings 
as Pluto does for its markdown cells: 
```julia
md"""
# Section Header
bla bla vla bla
"""
```
The big advantage of this would be proper syntax highlighting in editors.

**Comment by fredrikekre** [comment]
Seems reasonable, but would technically breaking if someone has an such a string in their code blocks.

**Comment by CarloLucibello** [comment]
yes, it would be technically breaking, but I doubt it will have any impact, not sure it is even worth tagging it as v3
