### ISSUE TITLE
Parsing fails for multiline comments and markdown with windows linebreaks

### ISSUE THREAD

**Issue by DrChainsaw** [fredrikekre/Literate.jl#165]
Thanks for this awesome package. Very powerful and easy to use!

Seems like the regex does not catch windows line breaks. As a piece of clear evidence that computers are consipiring against us, the method used in testing serves as a workaround :/

```julia
julia> mdstr = """
           md\"\"\"
           bla
           \"\"\"
           """

julia> mktempdir() do path
       testfile = joinpath(path,"testfile.md")
       write(testfile, mdstr)
       match(r"^md\"\"\"$\R^(\X*?)\R^\"\"\"$"m, read(testfile, String))
       end
RegexMatch("md\"\"\"\nbla\n\"\"\"", 1="bla")

# This file is created using "new file" in VS code
julia> read("mdtest.jl", String)
"md\"\"\"\r\nbla\r\n\"\"\""

julia> match(r"^md\"\"\"$\R^(\X*?)\R^\"\"\"$"m, read("mdtest.jl", String))
```

The regex works when tested in [Rubular](https://rubular.com/). Replacing `\R` with `(?:\r?\n)` does nothing, but removing the begin/end of line markers makes it work. 

This seems to be a way to create windows linebreaks inside Julia:

```julia
julia> mdstr = "md\"\"\"\r\nbla\r\n\"\"\""
"md\"\"\"\r\nbla\r\n\"\"\""

julia> mdstr == read("mdtest.jl", String)
true

julia> mktempdir() do path
       testfile = joinpath(path,"testfile.md")
       write(testfile, mdstr)
       match(r"^md\"\"\"$\R^(\X*?)\R^\"\"\"$"m, read(testfile, String))
       end
```

**Comment by fredrikekre** [comment]
Thanks, I thought it was happening after (https://github.com/fredrikekre/Literate.jl/blob/65f55d3f7a41af5f621cb987374887fa55a5891f/src/Literate.jl#L151) but that is just pushing replacements to a vector and doing the replacement later
