### ISSUE TITLE
Failure with space in filenames

### ISSUE THREAD

**Issue by blegat** [fredrikekre/Literate.jl#168]
I had a examples with a file named "Bound on Global Extremum.jl".
It worked before but with the lastest version of Literate and Documenter, it fails with
```
ERROR: LoadError: invalid '@example' syntax: @example Bound on Global Extremum
```

See https://github.com/jump-dev/SumOfSquares.jl/pull/201/checks?check_run_id=3464443765#step:5:116
Maybe Literate should replace spaced by underscores when generating the label to be used with `@example` so that there is no space in the name.

**Comment by fredrikekre** [comment]
I don't think anything in Literate has changed here, so probably a Documenter change. Probably before the name of the example in Documenter would be just "Bound" but now seems like there is some extra restrictions.

> Maybe Literate should replace spaced by underscores when generating the label to be used with @example so that there is no space in the name.

Sure, seems like a good idea.
