### ISSUE TITLE
Julia code quoting for Jekyll

### ISSUE THREAD

**Issue by cormullion** [fredrikekre/Literate.jl#17]
I didn’t work out how to format Julia code with the 

    {% highlight julia %}
    
    {% endhighlight julia %}

that Jekyll wanted, rather than the

    ```julia
     
    ```

Is there a setting or is it a job for `preprocess`?

**Comment by fredrikekre** [comment]
Doesn't the `codefence` kwarg work for this? E.g.
```julia
Literate.markdown(...; codefence = "{% highlight julia %}" => "{% endhighlight julia %}")
```

**Comment by cormullion** [comment]
Ha, you're right, my mistake. I think I saw `documenter` and assumed wrongly that it was just interacting with Documenter syntax...
