### ISSUE TITLE
embed svg instead of png for plot

### ISSUE THREAD

**Issue by tpapp** [fredrikekre/Literate.jl#182]
I would like 

```
# # Experiment with Literate

using PGFPlotsX
Plot(Table(1:10, 1:10))
```

rendered with `Literate.markdown("index.jl", ".", flavor = Literate.CommonMarkFlavor(), execute = true)` to embed the plot as **svg instead of png**.

Looking at [the source](https://github.com/fredrikekre/Literate.jl/blob/29d33b78073925f7de741dc4b319d0250e178a26/src/Literate.jl#L556), this seems to be hardcoded. Ok if I make a PR to customize this, or is there an easier way?

**Comment by fredrikekre** [comment]
Sure, that would be fine. I just didn't know if there was a common enough way to embed svg in markdown.

**Comment by tpapp** [comment]
Cf #126.
