### ISSUE TITLE
Allow AbstractDict config

### ISSUE THREAD

**Issue by tlienart** [fredrikekre/Literate.jl#185]
Is there a reason why `config` is type restricted to `Dict` and not to `AbstractDict`? e.g. here:

https://github.com/fredrikekre/Literate.jl/blob/ebe1cfd48305f5e1b98ee66e8d2cd55c5616fad5/src/Literate.jl#L126 

Not a big deal but relaxing it would allow to use `LittleDict` for instance.

**Comment by fredrikekre** [comment]
No reason.
