### ISSUE TITLE
Literate will ask for SSH passphrase multiple times

### ISSUE THREAD

**Issue by cjalmeida** [fredrikekre/Literate.jl#197]
Similar issue to #196, Literate.jl will still ask for a passphrase if your SSH key is password protected. 

The fix in #194 introduces a regression where it ignores ssh-agent variables. It should use `withenv` instead of `setenv`.

The actual fix requires add adding the `BatchMode` option to `GIT_SSH_COMMAND`.

**Comment by fredrikekre** [comment]
It shouldn't ask at all -- what version of `git` are you using?

> The fix in https://github.com/fredrikekre/Literate.jl/pull/194 introduces a regression where it ignores ssh-agent variables. It should use withenv instead of setenv.

It is better to use `addenv` (a7bdb8cdbe51a2659abf005228e9e5c63b5bb652).

> The actual fix requires add adding the BatchMode option to GIT_SSH_COMMAND.

Yea, maybe this is a better way to supress prompts compared to 75f4e21381dcbdf4914e199ad4e39027594c8347 ?
