### ISSUE TITLE
Escaping link interpretation for Documenter links

### ISSUE THREAD

**Issue by j-fu** [fredrikekre/Literate.jl#198]
Hi, 
when I try to put documenter links of the kind 
```
[`mymethod`](@ref)
```
into a literate document (with `documenter=false`), Literate seems to strip away the link and keeps just
```
`mymethod`
```

What in the moment works for me is to write
```
[`mymethod`](@@ref)
```
Literate does not touch it, and I can replace `@@` by `@` in the postprocess.

**Comment by fredrikekre** [comment]
But stripping away Documenter specific syntax is the point of `documenter = false`?

**Comment by j-fu** [comment]
Well with `documenter=true` julia code will run during documentation, I want to avoid this due to potentially long run times.

Now I had a [look](https://github.com/fredrikekre/Literate.jl/blob/1ff48e95c6cd36e8b981097dfa858fbf5d26839f/src/Literate.jl#L210) at the implementation, so it seems that my way to circumvent link stripping appears to be reasonable and simply changing this behaviour would break other's code. 

So this appears to be a matter of taste and I close this in lieu of https://xkcd.com/1172/ ...

**Comment by fredrikekre** [comment]
> I want to avoid this due to potentially long run times.

While working on the documentation? You can use Documenters draft mode for that (which doesn't run code etc).
