### ISSUE TITLE
FR: Output to Quarto markdown flavour

### ISSUE THREAD

**Issue by svilupp** [fredrikekre/Literate.jl#199]
It would be amazing to add support Quarto markdown flavour

User story: As an analyst, I would like to write my script in Literate.jl format and easily convert to Quarto markdown to be able to further output to standard business outputs (PDF, presentations, etc)

What would it take? Would it be simply changing the codefence and adding a custom YAML header?

EDIT:

**Background on Quarto**:
- Quarto is a cross-platform cross-language open-source scientific and technical publishing system built on Pandoc
- It grew from Rmarkdown/knitr eco-system but has first-class support for Julia and Python
- There is already a good ecosystem: CLI, VS Code extension, JupyterLab support, caching support (for previews)
- It was introduced in JuliaCon 2022: [Reproducible Publications with Julia and Quarto | J.J. Allaire | JuliaCon 2022](https://www.youtube.com/watch?v=Y1uKNO32H_I&ab_channel=TheJuliaProgrammingLanguage)

**Markdown specs**: 
- [Julia reference](https://quarto.org/docs/computations/julia.html)
- It seems to support CommonMark (similar to Literate.jl): [reference](https://quarto.org/docs/reference/formats/markdown/commonmark.html)
- Code cells seem to have `{julia}` instead of julia codefence and there are some additional options, which I'm not sure how they would be passed: [Jupyter reference](https://quarto.org/docs/reference/cells/cells-jupyter.html)
- There is an additional YAML header where the user can provide some formatting configurations but also select which jupyter kernel to use for evaluation of the notebook (it's not clear to me how the julia Pkg environment is provided)

**Comment by fredrikekre** [comment]
Can you link to some description of what Quarto markdown flavor is?

**Comment by svilupp** [comment]
Apologies! I've beefed up the original post with some references and an introduction.

**Comment by svilupp** [comment]
Findings from a quick investigation: we get most of the functionality with the existing blocks, the only challenge I found is parsing the modifying attributes like `#| echo:false` that need to be inside of code blocks.

Goal: producing a .qmd file that corresponds to [Quarto specs](https://quarto.org/docs/computations/julia.html)

I've created a gist [here](https://gist.github.com/svilupp/25c02a7f347a63c99e61e5112b9ca6b8) with:
- target file `quarto_jl.qmd` that we would like to produce
- source file `quarto.jl` that we feed to Literate.jl

Code pipeline (from REPL):
```
using Literate
Literate.markdown("quarto.jl",flavor = Literate.CommonMarkFlavor(),codefence="```{julia}" => "```")
mv("quarto.md","quarto.qmd")
run(`quarto render quarto.qmd --to html`)
```

The only challenge I found was how to create a cell like this with `#| echo:false`-like statements
```
```{julia}
#| echo: false
#| output: false
using Pkg; Pkg.activate(".")
```

[Proposal](https://github.com/fredrikekre/Literate.jl/blob/1ff48e95c6cd36e8b981097dfa858fbf5d26839f/src/Literate.jl#L79):
- I think we could easily add a new flavour of markdown with its codefence [here](https://github.com/fredrikekre/Literate.jl/blob/1ff48e95c6cd36e8b981097dfa858fbf5d26839f/src/Literate.jl#L315)
- Writing the result to the right filename, probably use the keyword `literate_outputfile` in the config
- ? How to pass the code-block arguments? I think the rule that's not working is that comment expects a space (eg, `## Comment`), so [this regex](https://github.com/fredrikekre/Literate.jl/blob/1ff48e95c6cd36e8b981097dfa858fbf5d26839f/src/Literate.jl#L79) doesn't get triggered

I'm happy to open the PR but I'm not sure how to best tackle the 3rd bullet - any ideas?
