### ISSUE TITLE
Option to capture errors?

### ISSUE THREAD

**Issue by tpoisot** [fredrikekre/Literate.jl#201]
I'm using *Literate.jl* to work on some class material, and in specific cases, I would like a code block to result in an error -- this is mostly to walk students through reading error messages.

Is there a way to keep error messages (possibly on a per-chunk basis)?

**Comment by BeastyBlacksmith** [comment]
I am looking for the same thing but found that IOCapture does not capture the errors in `include_string`, probably because that function evaluates at toplevel?

CC: @mortenpi

**Comment by tpapp** [comment]
I am using 
```julia
try
    ... chunk ...
catch e
    showerror(stdout, e)
end
```
but having an option that wraps *all* code chunks in code like this would be great.

**Comment by tpapp** [comment]
I am working on a PR, I think I just need to customize `execute_block`.

**Comment by tpoisot** [comment]
Wonderful - thanks @fredrikekre

**Comment by fredrikekre** [comment]
I'm innocent -- thank @tpapp

**Comment by tpoisot** [comment]
Thanks @tpapp !
