### ISSUE TITLE
consecutive (or custom) image filenames

### ISSUE THREAD

**Issue by tpapp** [fredrikekre/Literate.jl#204]
Currently image filenames are calculated using a [hash](https://github.com/fredrikekre/Literate.jl/blob/9adfd9a38080c625e2cef08d0d4182bda1e7933d/src/Literate.jl#L624). This is useful, but when working on a document incrementally, the directory gets cluttered with a bunch of files that are no longer used.

Would it make sense to have an option to consecutively generates filenames with a counter? Eg `1.svg`, `2.svg`, etc.

**Comment by fredrikekre** [comment]
Sure, that is maybe better anyway. The idea with the hash was that you would have some connection between the code that generated the file, but not sure that is so useful.

**Comment by fredrikekre** [comment]
If you run multiple Literate files in the same directory you would get name-clashes though, which the current approach minimizes I guess. Documenter just uses a random number, but not sure that is much better than the current hash method.

**Comment by tpapp** [comment]
Yes, I would prefer the clashing filenames to be silently overwritten. I would not recommend this as the default though.

**Comment by fredrikekre** [comment]
The names could perhaps be `${outputfilename}-${blocknumber}.svg`, that would avoid clashes.

**Comment by fredrikekre** [comment]
Fixed in https://github.com/fredrikekre/Literate.jl/pull/205, released in 2.14.0 (https://github.com/JuliaRegistries/General/pull/68765).
