### ISSUE TITLE
suggestion: mention MarkdownTables.jl in the manual

### ISSUE THREAD

**Issue by tpapp** [fredrikekre/Literate.jl#206]
I wrote a tiny package https://github.com/tpapp/MarkdownTables.jl, which takes a Tables.jl-compliant table, prints it as Markdown, and wraps it in a `DisplayAs` object, so it can be used as
```julia
some_table |> markdown_table()
```
or similar with Literate.jl. It essentially makes the trick mentioned in the manual easy to apply for tables.

**Comment by fredrikekre** [comment]
Feel free to make a PR!
