### ISSUE TITLE
Question: checking for all `[deps]` in `docs/Project.toml`

### ISSUE THREAD

**Issue by JeffFessler** [fredrikekre/Literate.jl#212]
I test my Literate examples on my local host. After they work locally, I push them to a PR in github.
Often I forget to include some package(s) in the `[deps]` for my `docs/Project.toml`.

My local test passes, even though it shouldn't, because the default [LOAD_PATH](https://docs.julialang.org/en/v1/base/constants/#Base.LOAD_PATH) includes `"v#.#"`, so my local test run is getting the needed package from my base environment without warning me that it is missing from `docs/Project.toml`.

Oddly, even when I am missing an deps entry, the CI on github still runs fine and reports "All checks passed" instead of reporting my omission.  But if I click "Show all checks" and look at the details for the Documentation run, then I see that the "Build and Deploy" stage actually failed due to the missing `[deps]` entry.

* Is there a way to make my local test more faithful to the cloud environment so that if I am missing a deps entry then it will fail locally?  I've tried `JULIA_LOAD_PATH=docs/Project.toml:@stdlib` but that just caused many seemingly unrelated errors.
* Is there some other quick way (some script?) to verify whether all `using` and `import`s in a set of scripts are included in a `Project.toml`?
* Is there a way to get the CI for documentation building to *fail* rather than passing when there are such omissions?  (This might be a Documenter question...)
An answer to any of these would save me debugging time...  Thanks!

**Comment by mortenpi** [comment]
Do you have a link to an example CI run where you had this failure?

**Comment by JeffFessler** [comment]
This happens to me very often so it was easy to make an example:
https://github.com/JeffFessler/book-mmaj-demo/pull/12
github says it "passes" but the actual build fails.

**Comment by mortenpi** [comment]
The build on that PR was a success though? It does have heaps of warnings in the logs, but they're warnings, not errors. If you want them to be errors, you need to set `strict = true` in `makedocs`.

**Comment by JeffFessler** [comment]
Interesting.  I had not noticed that those were mere warnings because they are filled with serious sounding words like `failed` and `ArgumentError` and `UndefVarError`.
I guess I expected that an omitted deps would be an actual error, not just a warning.

I had studied the Literate docs pretty carefully, but I had overlooked the (apparently experimental) keyword option `strict = true` in the Documenter docs for [makedocs](https://documenter.juliadocs.org/stable/lib/public/#Documenter.makedocs).
Thanks for letting me know about that!
I added it and now things fail/work as expected.  I'll close this issue.
Hopefully the dialogue here will help someone else in the future.
Thanks much!

**Comment by fredrikekre** [comment]
> Is there a way to make my local test more faithful to the cloud environment so that if I am missing a deps entry then it will fail locally? I've tried JULIA_LOAD_PATH=docs/Project.toml:@stdlib but that just caused many seemingly unrelated errors.

Setting the load path should work, if you make sure the only entry is the docs/Project.toml environment. What unrelated errors did you see?
