### ISSUE TITLE
FR: Allow disabling the "generated with Literate" automatic text

### ISSUE THREAD

**Issue by Datseris** [fredrikekre/Literate.jl#22]
As the files I generate with Literate become more and more this text added at the end becomes more and more disruptive.

Literate is awesome and deserves credit, but I'd prefer to give credit only once at the start of my documentation instead of at the end of each page. I have added to my front page:
```
using [Material+MkDocs](https://squidfunk.github.io/mkdocs-material/),  [Literate.jl](https://github.com/fredrikekre/Literate.jl) and [Documenter.jl](https://github.com/JuliaDocs/Documenter.jl/).
```

This is a Feature Request for allowing the extra Literate text to be disabled from the `markdown` function.

**Comment by fredrikekre** [comment]
This is already implemented by giving `credit = false`, but I didn't wanna documente it cause I wanna farm those GitHub stars 😛
