### ISSUE TITLE
notebook() ignores outputdir?

### ISSUE THREAD

**Issue by SimonHansul** [fredrikekre/Literate.jl#238]
I try to have a script convert itself into a notebook (without execution), but save it to a parallel directory. 
However, no matter what I pass on as `outputdir`, the notebook is always saved directly to the working directory.

Executing 
```Julia
using Literate
Literate.notebook(@__FILE__, execute = false, outputdir = "notebooks")
```

results in:

```
[ Info: generating notebook from `C:\Users\...\MyProject\scripts\literatetest.jl`
[ Info: writing result to `C:\Users\...\MyProject\literatetest.ipynb`
"C:\\Users\\...\\MyProject\\literatetest.ipynb"
```

```Literate.notebook(@__FILE__, execute = false, outputdir = joinpath(pwd(), "notebooks"))``` does the same.

The problem also persists if I move the file directly into the working directory, or itry to convert a different script to notebook (or from the REPL), or omit the `execute` kwarg. 

Am I doing something wrong? Any help would be appreciated, finding this package extremely useful!

Working on Julia Version 1.10.1, Literate v2.16.1.

**Comment by fredrikekre** [comment]
`outputdir` is a positional argument, this works:
```julia
using Literate
Literate.notebook(@__FILE__, "notebooks"; execute = false)
```
(Sorry that I missed this issue until now)
