### ISSUE TITLE
Multi-line comments

### ISSUE THREAD

**Issue by yurivish** [fredrikekre/Literate.jl#26]
This is a great package! I wonder if multiline comments could be supported? In my experiments, a multiline comment (`#= ... =#`) turns into a code block prefaced with `@example testing`.

**Comment by fredrikekre** [comment]
Yea, no... That is too complicated for my simple parser :)

See some discussion here: https://github.com/fredrikekre/Literate.jl/issues/3#issuecomment-385968283 and my view on it here: https://github.com/fredrikekre/Literate.jl/issues/3#issuecomment-385990269

**Comment by yurivish** [comment]
OK. I just realized that while it is easy to parse `#=` on a starting line, it probably requires full Julia parsing to find the corresponding `=#` with full accuracy -- since there may be intervening `#= ... =#` _inside_ lines, or even inside strings...

What would your thoughts be on requiring that for Literate Julia files, the `#=` and corresponding `=#` must each be at the start of their respective lines?

**Comment by fredrikekre** [comment]
> What would your thoughts be on requiring that for Literate Julia files, the #= and corresponding =# must each be at the start of their respective lines?

Makes sense to me, and is probably how I would do it.

**Comment by yurivish** [comment]
Great. Time to test out the package-editing workflow with Pkg3!

**Comment by KristofferC** [comment]
😅

**Comment by j-fu** [comment]
See https://github.com/fredrikekre/Literate.jl/pull/122 :)
