### ISSUE TITLE
Use pretty_tables in Literate output

### ISSUE THREAD

**Issue by tpoisot** [fredrikekre/Literate.jl#262]
I am trying to use [PrettyTables](https://ronisbr.github.io/PrettyTables.jl/stable/) with Literate, and the output is given as a code block (as opposed to a table that is rendered as such in the html):

![Screenshot_20241017_164913](https://github.com/user-attachments/assets/b866f6f1-9cc1-4de3-ae93-cd4abc71cec6)

Is there an easy fix to this?

**Comment by fredrikekre** [comment]
Literate relies on the `show` system but it looks like PrettyTables doesn't? This works
```
using PrettyTables

struct PrettyTable
    args
    kwargs
    PrettyTable(args...; kwargs...) = new(args, kwargs)
end

function Base.show(io::IO, ::MIME"text/plain", pt::PrettyTable)
    PrettyTables.pretty_table(io, pt.args...; pt.kwargs...)
end

function Base.show(io::IO, ::MIME"text/markdown", pt::PrettyTable)
    PrettyTables.pretty_table(io, pt.args...; pt.kwargs..., backend = Val(:markdown))
end

x = rand(10, 2)

pt = PrettyTable(x, header = ["A", "B"], alignment = :c)
```
Perhaps something like that already exist in PrettyTables?

**Comment by tpoisot** [comment]
Good question - I opened an issue there. Thanks!
