### ISSUE TITLE
example does not work for notebook

### ISSUE THREAD

**Issue by Roger-luo** [fredrikekre/Literate.jl#27]
I tried

```julia
using Plots
x = range(0, stop=6π, length=1000)
y1 = sin.(x)
y2 = cos.(x)
plot(x, [y1, y2])
```

and I got this in the notebook output

```
0 5 10 15 -1.0 -0.5 0.0 0.5 1.0 y1 y2
```

Is this still because #15?

**Comment by Roger-luo** [comment]
ummm...tried again. This is what I got... Okay, I'll try if I can figure out how to fix myself.

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/8445510/44302266-aa554f80-a357-11e8-87b2-5f0ae1473c65.png">

**Comment by Roger-luo** [comment]
Why you don't have the last line? @jheinen 

> This notebook was generated using Literate.jl.

**Comment by fredrikekre** [comment]
What I meant is that you probably get a non-trusted notebook, and thats why the figure does not  show. You should be able to, from the Jupyter menu, say that you trust the notebook.

**Comment by KristofferC** [comment]
Indeed the "Non trusted" is visible in the screenshot.

Are there docs about this? Seems like a common gotcha.

**Comment by fredrikekre** [comment]
No, and I don't know why it happens sometimes, and sometimes not... Could add a note about it though.

**Comment by Roger-luo** [comment]
I see… thx 😂👌

**Comment by zenna** [comment]
Just thought I'd add I was going to open an issue about this and github indicated #15 which led me here which made me realize that the notebook was non-trusted button.  I think this should be documented somewhere.  Could have saved me a lot of time re-executing code!
