### ISSUE TITLE
Change `#'` to simply `#` and require `##` for julia comments

### ISSUE THREAD

**Issue by fredrikekre** [fredrikekre/Literate.jl#3]
As discussed in https://discourse.julialang.org/t/ann-literate-jl/10651/9, using `#'` could be annoying, and julia comments are probably not as frequent as markdown input.

**Comment by Datseris** [comment]
Sounds like a good plan!

**Comment by KristofferC** [comment]
Agree that `#'` is a bit annoying. I think the `#` and `##` would probably work well.

**Comment by piever** [comment]
I also think it'd be better! Writing markdown spanning multiple lines is probably much more common in these kind of files and it's good to be able to use the editor shortcut for that.

**Comment by tshort** [comment]
How about including the multi-line comment field, too? It'd be even easier to include/format markdown there. 
```julia
#=
# heading

Some *text*...
=#
```

Another option is to include something in the leading indicator like `#=md`.

**Comment by fredrikekre** [comment]
> How about including the multi-line comment field, too?

I am not a big fan of multiline comments personally, It breaks syntax highlighting in some editors, complicates the quite minimal current syntax, and makes parsing of the source file more complicated. I think going with #4 is good enough, which should make it much simpler to comment-toggle the markdown lines, if you prefer to edit them without the leading `# `, and then toggle back.

**Comment by JeffreySarnoff** [comment]
Multiline comments provided limited literacy before it was fashionable.  I still use them when, six months hence, l need to remember a subtle something. 
Would there be a way to adapt Julia's block delimiters and use `##=` .. `#=#` without requiring mensurable effort.

Either way, I am appreciative of the work.  Maybe now, I can provide the sort of microtutorial others will utilize.  Thank you.

**Comment by waldyrious** [comment]
Related to @aalexandersson's point above, and just for reference (I'm not convinced this would be preferable to `#` v.s `##`), back in 2013 I filled https://github.com/jashkenas/docco/issues/216, which suggests omitting the space after the comment marker to distinguish intentional documentation from (temporarily?) commented-out code. Thought I'd mention that option here, for completeness.
