### ISSUE TITLE
Comments in code

### ISSUE THREAD

**Issue by MikeInnes** [fredrikekre/Literate.jl#37]
In my scripts I have something like this, with the intention that you can easily enable GPU support if you have it set up.

```
using Flux
# using CuArrays
```

Unfortunately Literate puts the commented code into a plain text cell. I'm not sure what the best way around this is, but perhaps it's a reasonable heuristic to treat comments as code when there's no space like this?

**Comment by fredrikekre** [comment]
There are `##` syntax for this purpose, see https://fredrikekre.github.io/Literate.jl/stable/fileformat.html#Syntax-1

**Comment by MikeInnes** [comment]
Ah, thanks. I had been using the [internal comments](https://github.com/fredrikekre/Literate.jl/blob/master/src/Literate.jl#L10) as documentation, so that's useful to know about :)

I think for my purposes it'd be sufficient to just do a find-and-replace in preprocessing here, so I'll go ahead with that.
