### ISSUE TITLE
Plots shown three times in nbviewer.js

### ISSUE THREAD

**Issue by improbable22** [fredrikekre/Literate.jl#55]
When viewing notebooks made by Literate.jl using https://github.com/tuxu/nbviewer-app/ , plots are shown three times. This doesn't happen for notebooks saved directly by Jupyter. 

The issue on that side is  https://github.com/kokes/nbviewer.js/issues/28 (starting with a now resolved problem, in which very little was shown). Here's the test document given there, all three versions are now the same size 
```
# Test with a plot

sum(i for i=1:100)
# -
using Plots
plot(rand(20))

# The end.
```
Here's what fits on my screen: 
<img width="327" alt="screen shot 2019-02-09 at 12 05 31" src="https://user-images.githubusercontent.com/29553230/52519907-0cd23d00-2c63-11e9-9ea0-e2add4cb7f99.png">

**Comment by KristofferC** [comment]
AFAIU, Literate just provide multiple MIME types of the same object and it is up to the renderer to chose how this should be displayed.

**Comment by improbable22** [comment]
OK, after digging a bit I do think the issue is most likely on the other end. I pasted in there lots of details:  https://github.com/kokes/nbviewer.js/issues/28#issuecomment-462065653

May I ask, why include multiple formats in the Literate output at all? Is this in case something is incompatible with SVG? 

Something about this also confuses Jupyter itself, which does not seem to show the graphs when opening a notebook produced by Literate.

**Comment by KristofferC** [comment]
> Something about this also confuses Jupyter itself, which does not seem to show the graphs when opening a notebook produced by Literate.

That sounds like you are not "trusting" the notebook (which is needed to render svg), ref https://ipython.org/ipython-doc/3/notebook/security.html#explicit-trust.

**Comment by improbable22** [comment]
Oh awesome, thank you! I would never have found the "trust" concept.

The remaining question on the other thread seems to be whether there is a standard order of preference for formats which ought to be used. I would guess vector > raster > text but beyond that I don't know.

**Comment by improbable22** [comment]
Solved on the other side (https://github.com/kokes/nbviewer.js/issues/28) thus closing here.
