### ISSUE TITLE
Introduce negation filters

### ISSUE THREAD

**Issue by kellertuer** [fredrikekre/Literate.jl#59]
Would it be possible to have negative filters as well?
For example If I write some code, that I want to use in a `Documenter.jl` documentation, I could want to enhance keywords to be linked to the corresponding page, for example when speaking about my own Type `MyType`. In the code for `Literate.jl`. For both other cases (notebook and plain Julia) I don't want to clutter the notebook/example.

So for example I would write

```
#md # Now let's use [`MyType`](@ref)
#nb # Not let's use MyType
#jl # Now let's use MyType
```
but it would be shorter to write for example
```
#md # Now let's use [`MyType`](@ref)
#!md # Not let's use MyType
```
to say that the first line should be used in markdown and the second for all other types of renderings.

Of course for this example one could argue that the notebook might want to have just a marked up `MyType` so that we still need three versions, but then the example would just not fit my feature request ;)

Besides that: The idea of the package is quite nice, thanks for providing it :)

**Comment by fredrikekre** [comment]
For the particular case of `@ref`s, Literate will remove them by default, see https://fredrikekre.github.io/Literate.jl/stable/documenter/ but maybe `#!md` etc might be useful too.

**Comment by kellertuer** [comment]
Ah, I did not see, that they are removed for scripts, that's nice and avoids the double text I had for now;
but actually my main point was to illustrate an `#!md`
