### ISSUE TITLE
File size when embedding plots

### ISSUE THREAD

**Issue by improbable22** [fredrikekre/Literate.jl#61]
I have some unreasonably large notebooks, because Literate.jl seems to be including several versions of every plot. Is there, or should there be, a way to disable this? I can't find anything in the documentation. 

Adding `Plots.default(fmt=:png)` results in the displayed version being the PNG, but not only does this seem to be included twice, but the SVG version (which is huge because there are many plot points) still gets saved. 

The generated notebook looks a bit like this: 
```
{
 "cells": [
  {
   "outputs": [],
   "cell_type": "code",
   "source": [
    "using Plots\n",
    "Plots.default(fmt=:png)"
   ],
   "metadata": {},
   "execution_count": 1
  },
  {
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": "Plot{Plots.GRBackend() n=1}",
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAfQAAAEsCAIAAAC62dafAAAABmJLR0QA...",
      "text/html": [
       "<img src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAfQAAAEsCAIAAAC62dafAAAABmJLR0QA...\">"
       ],
      "image/svg+xml": [
       "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n",
       "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"500\" height=\"300\" viewBox=\"0 0 2000 1200\">\n",
       "<defs>\n",
       "  <clipPath id=\"clip4400\">\n",
       "    <rect x=\"0\" y=\"0\" width=\"2000\" height=\"1200\"/>\n",
       "  </clipPath>\n",
       "</defs>\n",
```

**Comment by fredrikekre** [comment]
Thats how notebooks work -- generate different output and let the frontend decide which one to display.

**Comment by improbable22** [comment]
I understand that providing fall-back options is a generally a good thing, but my browser struggles a bit with 50MB notebooks, and I don't need to save all the thousands of plot points exactly. 

When running the notebook directly in Jupyter/IJulia, only one version is saved, and if this is the PNG then the file is much smaller & quicker.

**Comment by fredrikekre** [comment]
> When running the notebook directly in Jupyter/IJulia, only one version is saved

Are you sure? I have basically copied `IJulias` implementation here.

**Comment by improbable22** [comment]
Here's a quick test, first generating a 30MB file from Literate, and then re-running it by hand, 250kB:  [test61.zip](https://github.com/fredrikekre/Literate.jl/files/3191909/test61.zip)

I have just updated everything, versions: 
```
(v1.1) pkg> st
    Status `~/.julia/environments/v1.1/Project.toml`
  [7073ff75] IJulia v1.18.1
  [98b081ad] Literate v1.1.0
  [91a5bcdd] Plots v0.25.1
  ...
```

**Comment by fredrikekre** [comment]
Okay, will have a look later.

**Comment by KristofferC** [comment]
svg doesn't seem to be embedded in the jupyter notebook.

**Comment by improbable22** [comment]
Many thanks! 

Yes, `test61jupyter.ipynb` does not contain the SVG, only PNG, because of `default(fmt=:png)`. If I remove that, then Jupyter saves the SVG instead, and the file is again huge.

**Comment by fredrikekre** [comment]
So this happens because Plots has their own implementation of `IJulia.display_dict` and only outputs one version: https://github.com/JuliaPlots/Plots.jl/blob/0735a3475c3747bbac92925cdc58668bbb74929b/src/ijulia.jl#L36

**Comment by KristofferC** [comment]
Perhaps it makes sense to somehow be able to set what mime types should be rendered?

**Comment by tkf** [comment]
FYI I created [DisplayAs.jl](https://github.com/tkf/DisplayAs.jl) a while ago to control/limit MIME to be used for `display`.  You can use it like

```julia
x |> DisplayAs.PNG
```
