### ISSUE TITLE
Issue with Reexport?

### ISSUE THREAD

**Issue by briochemc** [fredrikekre/Literate.jl#62]
I am unsure but it seems that generating and executing a notebook prevents Reexport.jl from working properly. 

#### MWE:
First, I create and save a sparse matrix using JLD2 via:
```julia
using JLD2, SparseArrays
M = sprand(10, 10, 0.5)
@save "a_sparse_matrix.jld2" M
```
Then I have this `load_a_sparse_matrix.jl` file to load the matrix `M` and do a simple operation on it (just doing `-M` here) using a module `Foo`. (Note the module `Foo` must reexport `SparseArrays` to be able to do operations on, well, sparse arrays like `M`.) I want to generate a notebook out of this file using Literate. Contents:
```julia
# Create a little module to load a sparse array using JLD2

module Foo # begin module
using JLD2
using Reexport
@reexport using SparseArrays
function load()
    @load "a_sparse_matrix.jld2" M
    return -M
end
end # module

# Use the new module

using .Foo

# Load the sparse array

A = Foo.load()
```

From there, starting a new Julia session and doing
```julia
include("load_a_sparse_matrix.jl")
```
works fine, but starting a new Julia session and doing
```julia
using Literate
Literate.notebook("load_a_sparse_matrix.jl", "./")
```
throws an error because `SparseArrays` was not reexported somehow and thus the `-M` operation is not possible for the reconstructed type:
```julia
ERROR: LoadError: MethodError: no method matching -(::getfield(JLD2.ReconstructedTypes, Symbol("##SparseArrays.SparseMatrixCSC{Float64,Int64}#364")))
``` 
What am I doing wrong? Should I not use Reexport.jl at all?

**Comment by fredrikekre** [comment]
I'm not sure whats happening here, but I don't think it is a Literate.jl bug, the same error happens for e.g.
```
module A
    include("load_a_sparse_matrix.jl")
end
```
(which basically is what Literate does) so it looks like Reexport only works when Reexporting to Main.
