### ISSUE TITLE
Print to stdout not printed in the rendered html.

### ISSUE THREAD

**Issue by kellertuer** [fredrikekre/Literate.jl#63]
I am trying to capture printed parts, as the documentation says at

https://fredrikekre.se/Literate.jl/latest/generated/example/#Output-Capturing-1

but even there, just the returned value of `foo()`is displayed and I noticed the same. Is that a problem of Literate.jl or a setting that changed in Documenter.jl?

**Comment by fredrikekre** [comment]
I believe that if you return something else than `nothing` from the block Documenter will only display that result and ignore the stdout output.

**Comment by fredrikekre** [comment]
Indeed; https://github.com/JuliaDocs/Documenter.jl/blob/ea7975c47a19fc7bc5afea711383cf19406de97f/src/Expanders.jl#L575-L579

**Comment by fredrikekre** [comment]
`IJulia` displays both though, so could be argumented that Documenter should do the same. Maybe open an issue at the Documenter.jl repo?

**Comment by kellertuer** [comment]
Thanks for looking that up so fast! Well for now I can trick that into doing two cells one performs the algorithm with prints and has a nothing to see the prints, the other contains just the variable the result is stored in to see the result. But yes I will open an Issue at Documenter then. You're documentation is for now misleading, btw.

**Comment by fredrikekre** [comment]
> Your documentation is for now misleading, btw.

Ah, good catch. That was probably only tested for notebook output.
