### ISSUE TITLE
Suggestion: Turn admonitions into quotes for notebooks?

### ISSUE THREAD

**Issue by briochemc** [fredrikekre/Literate.jl#64]
It seems admonitions like `!!! note` are not available in notebooks (https://github.com/jupyter/notebook/issues/1292).
Maybe Literate.jl could translate those into quotes by default via `Literate.notebook`?
For example, take
```julia
# !!! note
#     This is a warning
```
as a source file.
It would become a Documenter admonition via `Literate.markdown` by simply stripping the `# ` at the start, i.e., give:
```markdown
!!! note
    This is a warning
```
But via `Literate.notebook`, it would look more like
```markdown
> *Note*:
> This is a warning
```
which renders sort-of-like a Documenter admonition.
> *Note*:
> This is a warning

**Comment by fredrikekre** [comment]
Possibly, but that requires Literate to look at the content and make sense of it (e.g. `Markdown.parse` it and look for admonitions or something) so it is not trivial.

**Comment by briochemc** [comment]
Would it be possible using another "tag" like `#md` and `#nb`? Maybe `#note`? So it would look like
```julia
#note # This is a warning
```
and generate
```markdown
!!! note
    This is a warning
```
via `Literate.markdown` and
```markdown
> *Note*:
> This is a warning
```
via `Literate.notebook`.

**Comment by fredrikekre** [comment]
Its pretty easy to do that transformation yourself, e.g.
```julia
julia> function md_note(str)
           str = replace(str, r"^#note # (.*)$"m => s"""
           # !!! note
           #     \1""")
           return str
       end
md_note (generic function with 1 method)

julia> function nb_note(str)
           str = replace(str, r"^#note # (.*)$"m => s"""
           # > *Note*
           # > \1""")
           return str
       end
nb_note (generic function with 1 method)

julia> using Literate

julia> Literate.markdown("example.jl", "tmp/"; preprocess = md_note);

julia> Literate.notebook("example.jl", "tmp/"; preprocess = nb_note);
```

**Comment by moustachio-belvedere** [comment]
Added a pull request to include this in documentation https://github.com/fredrikekre/Literate.jl/pull/115
