### ISSUE TITLE
Documentation is down

### ISSUE THREAD

**Issue by tkoolen** [fredrikekre/Literate.jl#66]
Thanks for the package!

Documentation seems to be down currently, I'm getting a 404.

**Comment by fredrikekre** [comment]
Hmm, what link is that? https://fredrikekre.github.io/Literate.jl/stable/ works for me.

**Comment by tkoolen** [comment]
`https://fredrikekre.se/Literate.jl/stable/`, the link for the documentation badge in the readme.

**Comment by tkoolen** [comment]
Actually, https://fredrikekre.github.io/Literate.jl/stable/ doesn't work for me either. Maybe it's cached for you?

**Comment by KristofferC** [comment]
Works for me on my phone. I remember there have been some very weird things before where some links work for some people but not other.

**Comment by tkoolen** [comment]
I'm on a different network now, and https://fredrikekre.github.io/Literate.jl/stable/ works now but https://fredrikekre.se/Literate.jl/stable/ still doesn't.

**Comment by fredrikekre** [comment]
> https://fredrikekre.se/Literate.jl/stable/, the link for the documentation badge in the readme.

But that is not the link in the README...

> Maybe it's cached for you?

I think it might have been the other way around and it was cached for you -- I changed some DNS records yesterday, and https://fredrikekre.github.io/Literate.jl/stable/ used to point to https://fredrikekre.se/Literate.jl/stable/ until yesterday.

> I'm on a different network now, and https://fredrikekre.github.io/Literate.jl/stable/ works now but https://fredrikekre.se/Literate.jl/stable/ still doesn't.

Great, that is how it is supposed to be :)

I purged the cache, so hopefully it have fixed itself then.

**Comment by tkoolen** [comment]
> But that is not the link in the README...

I can confirm that now. I'll close this issue; if I encounter any trouble when I'm back on the other network I'll reopen. Thanks!
