### ISSUE TITLE
Run `Literate.notebook` in the same process

### ISSUE THREAD

**Issue by dpsanders** [fredrikekre/Literate.jl#69]
If I am generating a notebook with e.g. `Plots.jl` plots, it would be useful to somehow run each `Literate.notebook()` call in the same process so that the loading and compilation only occur once.  Is this possible?

**Comment by fredrikekre** [comment]
I'm not sure what you mean. Literate does not start new processes.

**Comment by dpsanders** [comment]
I mean that when I run with `execute=true`, it takes much longer than with `execute=false`, and this time does not go down on the second run. Who is executing the notebook? I had a quick look at the source code but could not tell where this step happens.

**Comment by fredrikekre** [comment]
I mean, of course it takes longer to execute the code. 

> Who is executing the notebook?

Its the same Julia process (I am not using `nbconvert --execute` if that is what you are looking for), Literate just evaluate the expressions in the cells: https://github.com/fredrikekre/Literate.jl/blob/448f27dbe33d6e7e9ea7a1e88eb637df3daa3e2c/src/Literate.jl#L516

**Comment by dpsanders** [comment]
I see, nice, thanks a lot.

**Comment by dpsanders** [comment]
This has the problem that it tries to do interactive plots, so needs some way of opening those interactive plots. E.g. running it on a remote machine says that it can't find `xdg-open`, since it's trying to open the plots produced as it is not running actually them "inside" the notebook environment.

**Comment by fredrikekre** [comment]
Okay, do you have an example of that? In principle it shouldn't be any difference compared to what happens when IJulia evaluates cells.

**Comment by dpsanders** [comment]
e.g. running
```
using Plots

plot(sin)
```
causes GKSterm to flip open (on Mac) since that's what `Plots.jl` (with default GR backend) does when you try to plot outside a Jupyter notebook. Inside the notebook it somehow redirects the output such that no external program is called. (Sorry for my naive superficial view of things!)

**Comment by KristofferC** [comment]
Seems like a bug with Plots? I know Plots has a bunch of hardcoded stuff for eg Ijulia which might cause this.

**Comment by fredrikekre** [comment]
> e.g. running Literate.jl on the following input file:
> 
> using Plots
> 
> plot(sin)
> 

That example works fine for me on Linux, maybe its mac specific.
