### ISSUE TITLE
Spurious #- in Markdown

### ISSUE THREAD

**Issue by KristofferC** [fredrikekre/Literate.jl#70]
Running `markdown` on a file with the content

```
# SIMD sparse matrix dense vector multiplication

1 + 1
```

gives

````
```@meta
EditURL = "@__REPO_ROOT_URL__/"
```

SIMD sparse matrix dense vector multiplication

```@example sparse_matvec
1 + 1#-
```

*This page was generated using [Literate.jl](https://github.com/fredrikekre/Literate.jl).*
````

The `#-` in the `@example` block seems weird.

**Comment by fredrikekre** [comment]
Thanks, it should come after the code block. It is inserted to make a new block for the ad.

**Comment by fredrikekre** [comment]
I blame you here for not having an empty new line at the end of your file :D
