### ISSUE TITLE
Behavior change with comments within functions/expressions?

### ISSUE THREAD

**Issue by oschulz** [fredrikekre/Literate.jl#71]
Transforming an input like

```julia
function foo(x)
    # x times 2

    x * 2
end
```

with ```Literate.markdown("test.jl", ".", name = "test", documenter = false, credit = false)``` (using Literate v2.0.1) will split the function at the comment (`# x times 2`), resulting in an output like

`------------------------------------------------------------------------------------`
```julia
function foo(x)
```

x times 2

```julia
    x * 2
end
```
`------------------------------------------------------------------------------------`

so the Julia code becomes invalid. This used to be different in the past - though I'm not sure whether that was because the comment is indented or because it's within a function.

Would it be possible for Documenter to ignore comments within Julia functions/expressions/etc.?

**Comment by fredrikekre** [comment]
The idea is that you use `##` for regular Julia comments, since `#` is used to indicate markdown. However, I thought that you had to have it on the first column of the line. Do you happen to know when this changed?

**Comment by oschulz** [comment]
> The idea is that you use `##` for regular Julia comments

Yes, that's what I'm doing now - I never worried about it before, I thought it was a feature that comments within Julia functions/etc. were ignored. :-) Maybe it was just because they were indented? 

> Do you happen to know when this changed?

Sorry, not exactly - I noticed it because the tutorial of BAT.jl wouldn't build on Travis anymore. The last successful build of the docs was 20 days ago, according to Travis.

In any case, if the current behavior is the expected one, that's fine of course, `##` will do nicely.
I guess inspecting the Julia code to check if a comment is with a function/scope/etc. or not and then handle it differently may be overkill - and may also be surprising to the user.

Please feel free to close this issue.

**Comment by fredrikekre** [comment]
I added some extra information about this in https://github.com/fredrikekre/Literate.jl/commit/fb4059d28c7772e90ddf9a981a5089d44327a0c1 at least.

> I guess inspecting the Julia code to check if a comment is with a function/scope/etc. or not and then handle it differently may be overkill - and may also be surprising to the user.

Yea, currently Literate doesn't know anything (and doesn't have to) about the content, which makes it very simple.

**Comment by fredrikekre** [comment]
Do you have a link to the failure? I can not see a failing doc build on that repo.

**Comment by fredrikekre** [comment]
Okay, nvm, you relied on a undocumented feature for "continued documenter blocks" that I made a breaking change to in Literate v2.

**Comment by fredrikekre** [comment]
It looks like you intended them to be code comments, so definitely use `##` there. As you can see here https://bat.github.io/BAT.jl/stable/tutorial/#Likelihood-Definition-1 the function is broken up into multiple "continued" blocks, but Literate doesn't do this automatically anymore (since v2) so you need `#+` if you want that behavior.

**Comment by oschulz** [comment]
> Do you have a link to the failure? I can not see a failing doc build on that repo.

It was this one: https://travis-ci.com/bat/BAT.jl/builds/120794429

I changed the comments to `##` now, and all is well.

**Comment by oschulz** [comment]
Thanks again for the help!
