### ISSUE TITLE
Mention how to get rid of GR error messages in the docs?

### ISSUE THREAD

**Issue by devmotion** [fredrikekre/Literate.jl#73]
I was annoyed by all the error messages that I got when creating Plots with Literate + GR (using Plots) on Travis. Maybe it could be mentioned in the documentation that one can get rid of these error messages by setting the environment variable `GKSwstype` to `nul` before loading Plots (or GR) (see https://discourse.julialang.org/t/deactivate-plot-display-to-avoid-need-for-x-server/19359/2), e.g., by adding it to the documentation stage for Travis or `make.jl`?

**Comment by fredrikekre** [comment]
Hmm. I would rather not have to include stuff about other packages limitations in the docs. It has annoyed me a bit too (so thanks for the tip about the workaround) but since it does not affect the result output I don't think it is a big deal.

**Comment by devmotion** [comment]
Sure, that's fine with me!
