### ISSUE TITLE
empty deploy_folder for dev branch in travis

### ISSUE THREAD

**Issue by johnnychen94** [fredrikekre/Literate.jl#87]
The link is set to be:
`"@__NBVIEWER_ROOT_URL__/$(nbviewer_folder)/$(cardname).ipynb"`

and the generated URL is

`https://nbviewer.jupyter.org/github/johnnychen94/DemoCards.jl/blob/gh-pages//democards/simplest_demopage/dependencies/part2/simple_cameraman.ipynb`

in Travis-CI (missing a `dev` here). Just swapped into Github Action, and it works okay (in both `dev` and `stable` branch).

Although it looks perfect to me, it might be related to this part of the codes (line 233)

https://github.com/fredrikekre/Literate.jl/blob/00904a4c60ecc9e367e54bba61a0597ce6d2335d/src/Literate.jl#L230-L242

Not sure if it's related: I might incorrectly configure Travis-CI for Documenter, since I can only deploy a `dev` branch.

**Comment by briochemc** [comment]
Same issue here!

**Comment by briochemc** [comment]
BTW I think the same issue happens for the binder link.

**Comment by fredrikekre** [comment]
Sorry for this, maybe `TRAVIS_TAG` is set but empty instead of (as I assumed) unset.

**Comment by fredrikekre** [comment]
Fixed in version 2.2.1; https://github.com/JuliaRegistries/General/pull/6169.
