### ISSUE TITLE
execute markdown files

### ISSUE THREAD

**Issue by fredrikekre** [fredrikekre/Literate.jl#9]
People have suggested that it should be possible to execute code and splice in the output in the markdown files. Example:
```
# # Hello

foo(a, b) = a + b
foo(2, 3)
```

would result in a markdown file with

````
# Hello

```julia
foo(a, b) = a + b
foo(2, 3)
```

```
5
```
````

See https://discourse.julialang.org/t/ann-literate-jl/10651

**Comment by piever** [comment]
To clarify what I meant on Discourse, what I would be curious was whether it was easy/feasible to generalize this package to cases that won't be included as documentation of a package (e.g. the markdown for a presentation). I see three ways forward:

- Add the feature here directly
- See whether Documenter can be used for this case as well (meaning whether Documenter or its internals provides some function to execute code in the markdown even when there is no package structure and it really just is a markdown file
- Figure out what is the minimum structure that Documenter needs to run and suggest the user to create a mini package with just that structure instead (or maybe provide some automated procedure to generate it)

**Comment by fredrikekre** [comment]
Is the feature you want what my example in the first post here describes?

**Comment by KristofferC** [comment]
> See whether Documenter can be used for this case as well (meaning whether Documenter or its internals provides some function to execute code in the markdown even when there is no package structure and it really just is a markdown file

Ref:
https://github.com/JuliaDocs/Documenter.jl/pull/529

**Comment by piever** [comment]
@fredrikekre yes, that's the feature I want. I hacked my way around it by creating a small folder `docs` with the required structure (`src`, `build` and `make.jl`) and running `makedocs` on that, but it'd be nice to have a more streamlined experience for users who only really need one markdown file.

**Comment by fredrikekre** [comment]
> yes, that's the feature I want

Ok, that is trivial to implement, I just need to be bored enough with other things :smile:

**Comment by fredrikekre** [comment]
Actually, you can already do this with Literate/Documenter:
```
shell> ls
test.jl

shell> cat test.jl
# # Hello
#
# Some text

foo(a, b) = a + b
foo(2, 3)
```
```julia
julia> import Literate; Literate.markdown("test.jl", "src"; name = "index");

julia> using Documenter; makedocs();
```

which generates the following (executed) markdown:
````
# Hello

Some text

```julia
foo(a, b) = a + b
foo(2, 3)
```
```
5
```
````

and if you apply 
```diff
diff --git a/src/Writers/HTMLWriter.jl b/src/Writers/HTMLWriter.jl
index 6eea033..764fd84 100644
--- a/src/Writers/HTMLWriter.jl
+++ b/src/Writers/HTMLWriter.jl
@@ -111,7 +111,6 @@ getpage(ctx, navnode::Documents.NavNode) = getpage(ctx, navnode.page)
 
 
 function render(doc::Documents.Document)
-    !isempty(doc.user.sitename) || error("HTML output requires `sitename`.")
 
     ctx = HTMLContext(doc)
     ctx.search_index_js = "search_index.js"
```
to Documenter, you can render a HTML page with 
```
using Documenter; makedocs(format = :html);
```

**Comment by piever** [comment]
Thanks a lot this, works perfectly for my use case.

**Comment by mauro3** [comment]
Running above example does not give me a executed markdown file.  I suspect it needs some updates along the lines of https://juliadocs.github.io/Documenter.jl/stable/man/other-formats/. However, I'm after the HTML and that works.
Maybe the example could this be added to the documentation for an and the patch to documenter included?  Seems useful.
Even more useful would be to have a `Literate.html(...)` function.

**Comment by baggepinnen** [comment]
I also wanted this functionality quite badly, and didn't find Documenter that convenient. I created the glue package https://github.com/baggepinnen/LiterateWeave.jl
that calls literate -> weave -> nice pdf with figures -> :+1:

**Comment by liuyxpp** [comment]
It would be great if Literate.jl can handle the code running internally. I don't like Documenter.

Also, if there is also a convenient way to configure the code fence, from ```julia to something like {% highlight julia %}, which is extremely helpful to directly generate markdown for Jekyll?

**Comment by fredrikekre** [comment]
> Also, if there is also a convenient way to configure the code fence, from ```julia to something like {% highlight julia %}, which is extremely helpful to directly generate markdown for Jekyll?

See the `codefence` config https://fredrikekre.github.io/Literate.jl/stable/outputformats/#Configuration-1.

**Comment by liuyxpp** [comment]
Thanks! However, without the internal support of Literate.jl for running code and capturing its output, this approach will make the resulted markdown not processable for both Documenter and Weave. Thus it fails to address the very problem of making a markdown with output captured using Literate.jl.

A naive approach may be: use Documenter internally in Literate.jl to capture the output?

**Comment by fredrikekre** [comment]
It is not difficult to implement, just that no one has needed it enough to step up and implement it yet.
