### ISSUE TITLE
Inert Julia code?

### ISSUE THREAD

**Issue by cormullion** [fredrikekre/Literate.jl#91]
Is there a way to have some inert Julia code that looks like normal code but doesn’t run?

For example, if I wanted to say

```
# add this if you want to close the session
exit()
```

so that it looked like normal code but didn’t actually run?

**Comment by fredrikekre** [comment]
I am not sure I understand what end result you are after. But maybe you are looking for this:
- `inert.jl`:
  ````
  # This is a code-block inside a markdown section,
  # it is not considered code and therefore not run:
  #
  # ```julia
  # exit()
  # ```
  ````

- Output from `Literate.markdown("inert.jl", "out"; documenter=false)`:
  ````
  This is a code-block inside a markdown section,
  it is not considered code and therefore not run:
  
  ```julia
  exit()
  ```
  ````

**Comment by cormullion** [comment]
Thanks. I think I've managed to confuse myself using Literate and Franklin - I start to wonder what needs quoting/escaping and what doesn't... Sorry! 😊

**Comment by fredrikekre** [comment]
What is Franklin? :)

**Comment by cormullion** [comment]
They renamed JuDoc.jl... :)
