### ISSUE TITLE
Feature request: Filter lines ending by `#md`, `#jl` etc.

### ISSUE THREAD

**Issue by greimel** [fredrikekre/Literate.jl#92]
Is there a reason only `#src` is filtered at the end of a line?

I would like to have code only appear in the markdown version (or the the notebook), but I want it to be runnable in the source file.

Use case: I have a worked example for my package that I want to use for testing and illustration (with plots, but no tests). So, only the `.jl` file should contain tests, and only the `.md` file (that I weave to include in the documentation) should contain tests.

Btw: in the source it says that `#jl` is filtered at the end of the line, but this doesn't seem to be the case. 
https://github.com/fredrikekre/Literate.jl/blob/8e11b4ebe86c21ce0fefe23282aa4dd1ea2932f6/src/Literate.jl#L24

**Comment by fredrikekre** [comment]
#93

**Comment by fredrikekre** [comment]
Released in version 2.3.0.
